import { DocumentSchemaDefinition } from "../schema-types";

export const financeInvoice: DocumentSchemaDefinition = {
  key: "finance.invoice",
  name: "Vendor Invoice",
  industry: "FINANCE",
  description: "Extracts billing fields from a vendor invoice for AP automation.",
  version: 1,
  confidenceThreshold: 0.88,
  fields: [
    {
      name: "invoice_number",
      label: "Invoice Number",
      type: "string",
      required: true,
      aliases: ["Invoice Number", "Invoice #", "Inv. No.", "Invoice No"],
      pattern: "^[A-Za-z0-9-]{3,30}$",
    },
    {
      name: "vendor_name",
      label: "Vendor Name",
      type: "string",
      required: true,
      aliases: ["Vendor", "From", "Bill From", "Supplier"],
    },
    {
      name: "customer_name",
      label: "Customer / Bill To",
      type: "string",
      required: true,
      aliases: ["Bill To", "Customer", "Sold To"],
    },
    {
      name: "invoice_date",
      label: "Invoice Date",
      type: "date",
      required: true,
      aliases: ["Invoice Date", "Date"],
    },
    {
      name: "due_date",
      label: "Due Date",
      type: "date",
      required: false,
      aliases: ["Due Date", "Payment Due"],
    },
    {
      name: "subtotal",
      label: "Subtotal",
      type: "currency",
      required: false,
      aliases: ["Subtotal", "Sub Total"],
      pattern: "^\\$?[0-9][0-9,]*(\\.[0-9]{2})?$",
    },
    {
      name: "tax_amount",
      label: "Tax",
      type: "currency",
      required: false,
      aliases: ["Tax", "VAT", "Sales Tax"],
      pattern: "^\\$?[0-9][0-9,]*(\\.[0-9]{2})?$",
    },
    {
      name: "total_amount",
      label: "Total Amount Due",
      type: "currency",
      required: true,
      aliases: ["Total", "Total Due", "Amount Due", "Grand Total"],
      pattern: "^\\$?[0-9][0-9,]*(\\.[0-9]{2})?$",
    },
    {
      name: "currency",
      label: "Currency",
      type: "enum",
      required: false,
      aliases: ["Currency"],
      enumValues: ["USD", "EUR", "GBP", "CAD", "AUD"],
    },
  ],
};
